version: '3'

networks:
  selenium:
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always
    networks:
      - selenium

  app:
    build:
      context: .
    volumes:
      - .:/app
    command: sh -c "pytest -s test_PK.py"
    depends_on:
      - selenium
    networks:
      - selenium